ALTER TABLE "encounter_analytics" ADD COLUMN "encounter_type" text;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "session_duration" integer;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "chief_complaint" text;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "primary_diagnosis" text;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "vital_signs_recorded" boolean;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "cross_state_license" boolean;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "consent_obtained" boolean;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "informed_consent_type" text;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "clinical_notes_completed" boolean;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "note_signed_date" text;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "mental_health_screening" boolean;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "substance_use_screening" boolean;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "allergies_reviewed" boolean;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "coordination_with_pcp" boolean;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "follow_up_scheduled" boolean;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "care_plan_updated" boolean;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "clinical_protocol_approved_by" text;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "corporate_structure" text;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "physician_ownership_percentage" integer;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "clinical_decision_maker" text;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "clinical_decision_support" boolean;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "cds_alert_count" integer;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "technology_assessment" boolean;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "telehealth_id" text;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "provider_name" text;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "quality_measure_met" boolean;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "override_reason" text;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "controlled_substance_prescribed" boolean;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "medication_prescribed" text;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "prescriber_dea" text;--> statement-breakpoint
ALTER TABLE "encounter_analytics" ADD COLUMN "auto_refill_policy_corporate_mandated" boolean;--> statement-breakpoint
ALTER TABLE "medication_analytics" ADD COLUMN "controlled_substance_prescribed" boolean;--> statement-breakpoint
ALTER TABLE "medication_analytics" ADD COLUMN "auto_refill_policy_corporate_mandated" boolean;--> statement-breakpoint
ALTER TABLE "medication_analytics" ADD COLUMN "medication_prescribed" text;--> statement-breakpoint
ALTER TABLE "medication_analytics" ADD COLUMN "follow_up_scheduled" boolean;--> statement-breakpoint
ALTER TABLE "medication_analytics" ADD COLUMN "care_plan_updated" boolean;--> statement-breakpoint
ALTER TABLE "medication_analytics" ADD COLUMN "vital_signs_recorded" boolean;--> statement-breakpoint
ALTER TABLE "medication_analytics" ADD COLUMN "coordination_with_pcp" boolean;--> statement-breakpoint
ALTER TABLE "medication_analytics" ADD COLUMN "clinical_decision_support" boolean;--> statement-breakpoint
ALTER TABLE "medication_analytics" ADD COLUMN "cds_alert_count" integer;--> statement-breakpoint
ALTER TABLE "medication_analytics" ADD COLUMN "override_reason" text;--> statement-breakpoint
ALTER TABLE "medication_analytics" ADD COLUMN "substance_code" text;--> statement-breakpoint
ALTER TABLE "medication_analytics" ADD COLUMN "substance_quantity" integer;--> statement-breakpoint
ALTER TABLE "medication_analytics" ADD COLUMN "substance_expiry" text;